services:
  # A Docker web service
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: render.Dockerfile
    repo: https://github.com/langflow-ai/langflow
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: postgresql://langflowprod132_user:rRki7Eaz6grsxeLnmhHKU7QDTP17Lutx@dpg-d10mdta4d50c73auvh0g-a/langflowprod132
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: INFO